# Generated by Django 4.2.28 on 2026-03-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TenantSettings",
            fields=[
                ("tenant_id", models.UUIDField(primary_key=True, serialize=False)),
                ("company_name", models.TextField(blank=True, null=True)),
                ("tagline", models.TextField(blank=True, null=True)),
                ("logo_url", models.TextField(blank=True, null=True)),
                ("favicon_url", models.TextField(blank=True, null=True)),
                (
                    "primary_color",
                    models.CharField(
                        default="#2563EB",
                        help_text="Hex color e.g. #2563EB",
                        max_length=7,
                    ),
                ),
                ("secondary_color", models.CharField(default="#1E40AF", max_length=7)),
                ("accent_color", models.CharField(default="#10B981", max_length=7)),
                (
                    "subdomain",
                    models.TextField(
                        blank=True,
                        help_text="e.g. sunrise for sunrise.yourapp.com",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "custom_domain",
                    models.TextField(
                        blank=True,
                        help_text="e.g. crm.sunrisedevelopers.com",
                        null=True,
                    ),
                ),
                ("support_email", models.TextField(blank=True, null=True)),
                ("support_phone", models.TextField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.TextField(blank=True, null=True)),
                ("state", models.TextField(blank=True, null=True)),
                ("pincode", models.TextField(blank=True, null=True)),
                ("gstin", models.TextField(blank=True, null=True)),
                (
                    "pdf_header_text",
                    models.TextField(
                        blank=True, help_text="Text shown in PDF header", null=True
                    ),
                ),
                (
                    "pdf_footer_text",
                    models.TextField(
                        blank=True, help_text="Text shown in PDF footer", null=True
                    ),
                ),
                (
                    "signature_url",
                    models.TextField(
                        blank=True,
                        help_text="Authorized signatory signature image URL",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tenant_settings",
            },
        ),
        migrations.CreateModel(
            name="PaymentPlanTemplate",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant_id", models.UUIDField(db_index=True)),
                (
                    "name",
                    models.TextField(
                        help_text='e.g. "20:80 Plan", "My Construction Plan"'
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("20_80", "20:80 Plan"),
                            ("CONSTRUCTION_LINKED", "Construction Linked"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="CUSTOM",
                        max_length=30,
                    ),
                ),
                (
                    "stages",
                    models.JSONField(
                        help_text="Array of {name, percentage, days_from_booking} objects. percentages must sum to 100."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Use this plan as the default for new bookings",
                    ),
                ),
                ("owner_user_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "payment_plan_templates",
                "indexes": [
                    models.Index(fields=["tenant_id"], name="idx_ppt_tenant_id"),
                    models.Index(
                        fields=["tenant_id", "is_active"], name="idx_ppt_tenant_active"
                    ),
                ],
            },
        ),
    ]
