# Generated by Django 4.2.28 on 2026-03-02 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial_bookings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Broker",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("name", models.TextField()),
                ("email", models.TextField(blank=True, null=True)),
                ("phone", models.TextField()),
                ("company_name", models.TextField(blank=True, null=True)),
                ("rera_number", models.TextField(blank=True, null=True)),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=2,
                        help_text="Default commission rate in %",
                        max_digits=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("owner_user_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "brokers",
            },
        ),
        migrations.CreateModel(
            name="Commission",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("lead_id", models.BigIntegerField(db_index=True)),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "commission_amount",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("paid_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("owner_user_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        db_column="booking_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commissions",
                        to="bookings.booking",
                    ),
                ),
                (
                    "broker",
                    models.ForeignKey(
                        db_column="broker_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commissions",
                        to="brokers.broker",
                    ),
                ),
            ],
            options={
                "db_table": "commissions",
            },
        ),
        migrations.AddIndex(
            model_name="broker",
            index=models.Index(fields=["tenant_id"], name="idx_brokers_tenant_id"),
        ),
        migrations.AddIndex(
            model_name="broker",
            index=models.Index(fields=["status"], name="idx_brokers_status"),
        ),
        migrations.AddIndex(
            model_name="broker",
            index=models.Index(fields=["phone"], name="idx_brokers_phone"),
        ),
        migrations.AddIndex(
            model_name="broker",
            index=models.Index(
                fields=["owner_user_id"], name="idx_brokers_owner_user_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="broker",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "phone"), name="unique_broker_phone_per_tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="commission",
            index=models.Index(fields=["tenant_id"], name="idx_commissions_tenant_id"),
        ),
        migrations.AddIndex(
            model_name="commission",
            index=models.Index(fields=["broker"], name="idx_commissions_broker_id"),
        ),
        migrations.AddIndex(
            model_name="commission",
            index=models.Index(fields=["booking"], name="idx_commissions_booking_id"),
        ),
        migrations.AddIndex(
            model_name="commission",
            index=models.Index(fields=["status"], name="idx_commissions_status"),
        ),
        migrations.AddIndex(
            model_name="commission",
            index=models.Index(
                fields=["owner_user_id"], name="idx_commissions_owner_user_id"
            ),
        ),
    ]
