# Generated by Django 4.2.28 on 2026-03-02 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("brokers", "0001_initial_brokers"),
    ]

    operations = [
        migrations.AddField(
            model_name="broker",
            name="password_hash",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="broker",
            name="portal_email",
            field=models.TextField(
                blank=True,
                db_index=True,
                help_text="Login email for broker portal",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="BrokerSession",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "broker",
                    models.ForeignKey(
                        db_column="broker_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="brokers.broker",
                    ),
                ),
            ],
            options={
                "db_table": "broker_sessions",
                "indexes": [
                    models.Index(fields=["token"], name="idx_broker_sessions_token"),
                    models.Index(
                        fields=["broker"], name="idx_broker_sessions_broker_id"
                    ),
                ],
            },
        ),
    ]
