# Generated by Django 5.0.14 on 2025-11-23 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('title', models.TextField()),
                ('location', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('owner_user_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(blank=True, db_column='lead_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='crm.lead')),
            ],
            options={
                'db_table': 'meetings',
                'indexes': [models.Index(fields=['tenant_id'], name='idx_meetings_tenant_id'), models.Index(fields=['lead'], name='idx_meetings_lead_id'), models.Index(fields=['start_at'], name='idx_meetings_start_at'), models.Index(fields=['owner_user_id'], name='idx_meetings_owner_user_id')],
            },
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.CheckConstraint(check=models.Q(('end_at__gt', models.F('start_at'))), name='meetings_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'title', 'start_at'), name='unique_meeting_per_tenant'),
        ),
    ]
