# Generated by Django 4.2.28 on 2026-03-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="owner_user_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
