# Generated by Django 4.2.28 on 2026-03-02 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("name", models.TextField()),
                ("rera_number", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("location", models.TextField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.TextField(blank=True, null=True)),
                ("state", models.TextField(blank=True, null=True)),
                ("pincode", models.TextField(blank=True, null=True)),
                ("google_maps_url", models.TextField(blank=True, null=True)),
                ("total_units", models.IntegerField(default=0)),
                ("launch_date", models.DateField(blank=True, null=True)),
                ("possession_date", models.DateField(blank=True, null=True)),
                ("logo_url", models.TextField(blank=True, null=True)),
                ("banner_url", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("owner_user_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "projects",
            },
        ),
        migrations.CreateModel(
            name="Tower",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("name", models.TextField()),
                ("total_floors", models.IntegerField(default=1)),
                ("units_per_floor", models.IntegerField(default=1)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        db_column="project_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="towers",
                        to="inventory.project",
                    ),
                ),
            ],
            options={
                "db_table": "towers",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("unit_number", models.TextField()),
                ("floor_number", models.IntegerField()),
                (
                    "bhk_type",
                    models.CharField(
                        choices=[
                            ("STUDIO", "Studio"),
                            ("1BHK", "1 BHK"),
                            ("1.5BHK", "1.5 BHK"),
                            ("2BHK", "2 BHK"),
                            ("2.5BHK", "2.5 BHK"),
                            ("3BHK", "3 BHK"),
                            ("4BHK", "4 BHK"),
                            ("PENTHOUSE", "Penthouse"),
                            ("VILLA", "Villa"),
                            ("PLOT", "Plot"),
                            ("COMMERCIAL", "Commercial"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "carpet_area",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "built_up_area",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "super_built_up_area",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "facing",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NORTH", "North"),
                            ("SOUTH", "South"),
                            ("EAST", "East"),
                            ("WEST", "West"),
                            ("NORTH_EAST", "North East"),
                            ("NORTH_WEST", "North West"),
                            ("SOUTH_EAST", "South East"),
                            ("SOUTH_WEST", "South West"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "floor_rise_premium",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "facing_premium",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "parking_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "other_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("RESERVED", "Reserved"),
                            ("BOOKED", "Booked"),
                            ("REGISTERED", "Registered"),
                            ("SOLD", "Sold"),
                            ("BLOCKED", "Blocked"),
                        ],
                        db_index=True,
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                (
                    "reserved_for_lead_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("owner_user_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tower",
                    models.ForeignKey(
                        db_column="tower_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="inventory.tower",
                    ),
                ),
            ],
            options={
                "db_table": "units",
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["tenant_id"], name="idx_projects_tenant_id"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["tenant_id", "is_active"], name="idx_projects_tenant_active"
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "name"), name="unique_project_name_per_tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(fields=["tenant_id"], name="idx_units_tenant_id"),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(fields=["tower"], name="idx_units_tower_id"),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(fields=["status"], name="idx_units_status"),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(fields=["floor_number"], name="idx_units_floor_number"),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(fields=["bhk_type"], name="idx_units_bhk_type"),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.UniqueConstraint(
                fields=("tower", "unit_number"), name="unique_unit_number_per_tower"
            ),
        ),
        migrations.AddIndex(
            model_name="tower",
            index=models.Index(fields=["tenant_id"], name="idx_towers_tenant_id"),
        ),
        migrations.AddIndex(
            model_name="tower",
            index=models.Index(fields=["project"], name="idx_towers_project_id"),
        ),
        migrations.AddConstraint(
            model_name="tower",
            constraint=models.UniqueConstraint(
                fields=("project", "name"), name="unique_tower_name_per_project"
            ),
        ),
    ]
