# Generated by Django 4.2.28 on 2026-03-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial_inventory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="owner_user_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="owner_user_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
