# Generated by Django 5.0.14 on 2025-11-23 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='TODO', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('assignee_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('reporter_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('owner_user_id', models.UUIDField(db_index=True)),
                ('checklist', models.JSONField(blank=True, null=True)),
                ('attachments_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(db_column='lead_id', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.lead')),
            ],
            options={
                'db_table': 'tasks',
                'indexes': [models.Index(fields=['tenant_id'], name='idx_tasks_tenant_id'), models.Index(fields=['lead'], name='idx_tasks_lead_id'), models.Index(fields=['status'], name='idx_tasks_status'), models.Index(fields=['priority'], name='idx_tasks_priority'), models.Index(fields=['assignee_user_id'], name='idx_tasks_assignee'), models.Index(fields=['reporter_user_id'], name='idx_tasks_reporter'), models.Index(fields=['owner_user_id'], name='idx_tasks_owner_user_id')],
            },
        ),
    ]
