# Generated by Django 5.0.14 on 2025-11-23 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('name', models.TextField(default='Unnamed')),
                ('phone', models.TextField()),
                ('email', models.TextField(blank=True, null=True)),
                ('company', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('value_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('value_currency', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('owner_user_id', models.UUIDField(db_index=True)),
                ('assigned_to', models.UUIDField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Custom fields for storing dynamic key-value pairs', null=True)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('address_line1', models.TextField(blank=True, null=True)),
                ('address_line2', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('postal_code', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'leads',
            },
        ),
        migrations.CreateModel(
            name='LeadOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('position', models.DecimalField(decimal_places=3, max_digits=12)),
                ('board_id', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lead_orders',
            },
        ),
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('name', models.TextField()),
                ('order_index', models.IntegerField()),
                ('color_hex', models.TextField(blank=True, null=True)),
                ('is_won', models.BooleanField(default=False)),
                ('is_lost', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lead_statuses',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('type', models.CharField(choices=[('CALL', 'Call'), ('EMAIL', 'Email'), ('MEETING', 'Meeting'), ('NOTE', 'Note'), ('SMS', 'SMS'), ('OTHER', 'Other')], max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
                ('happened_at', models.DateTimeField()),
                ('by_user_id', models.UUIDField(db_index=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('file_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(db_column='lead_id', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead')),
            ],
            options={
                'db_table': 'lead_activities',
                'ordering': ['-happened_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadFieldConfiguration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('field_name', models.TextField(help_text='Field name/key (must be unique per tenant)')),
                ('field_label', models.TextField(help_text='Display label for the field')),
                ('is_standard', models.BooleanField(default=False, help_text='True if this is a standard Lead model field, False if custom field')),
                ('field_type', models.CharField(blank=True, choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('EMAIL', 'Email'), ('PHONE', 'Phone'), ('DATE', 'Date'), ('DATETIME', 'Date Time'), ('DROPDOWN', 'Dropdown'), ('MULTISELECT', 'Multi Select'), ('CHECKBOX', 'Checkbox'), ('URL', 'URL'), ('TEXTAREA', 'Text Area'), ('DECIMAL', 'Decimal'), ('CURRENCY', 'Currency')], default='TEXT', help_text='Data type for custom fields', max_length=20, null=True)),
                ('is_visible', models.BooleanField(default=True, help_text='Whether field is visible in UI')),
                ('is_required', models.BooleanField(default=False, help_text='Whether field is required')),
                ('is_active', models.BooleanField(default=True, help_text='Whether field is active')),
                ('default_value', models.TextField(blank=True, help_text='Default value for the field', null=True)),
                ('options', models.JSONField(blank=True, help_text='Options for dropdown/multiselect fields (array of strings)', null=True)),
                ('placeholder', models.TextField(blank=True, help_text='Placeholder text', null=True)),
                ('help_text', models.TextField(blank=True, help_text='Help text for the field', null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which field appears')),
                ('validation_rules', models.JSONField(blank=True, help_text='Custom validation rules (min, max, pattern, etc.)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lead_field_configurations',
                'ordering': ['display_order', 'field_label'],
                'indexes': [models.Index(fields=['tenant_id'], name='idx_lead_field_config_tenant'), models.Index(fields=['tenant_id', 'is_active'], name='idx_lead_field_config_active'), models.Index(fields=['tenant_id', 'is_standard'], name='idx_lead_field_config_standard'), models.Index(fields=['display_order'], name='idx_lead_field_config_order')],
            },
        ),
        migrations.AddConstraint(
            model_name='leadfieldconfiguration',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'field_name'), name='unique_field_config_per_tenant'),
        ),
        migrations.AddField(
            model_name='leadorder',
            name='lead',
            field=models.ForeignKey(db_column='lead_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='crm.lead'),
        ),
        migrations.AddIndex(
            model_name='leadstatus',
            index=models.Index(fields=['tenant_id'], name='idx_lead_statuses_tenant_id'),
        ),
        migrations.AddIndex(
            model_name='leadstatus',
            index=models.Index(fields=['order_index'], name='idx_lead_statuses_order_index'),
        ),
        migrations.AddConstraint(
            model_name='leadstatus',
            constraint=models.CheckConstraint(check=models.Q(('is_won', True), ('is_lost', True), _negated=True), name='lead_statuses_won_lost_check'),
        ),
        migrations.AddConstraint(
            model_name='leadstatus',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'name'), name='unique_lead_status_per_tenant'),
        ),
        migrations.AddField(
            model_name='leadorder',
            name='status',
            field=models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.CASCADE, related_name='lead_orders', to='crm.leadstatus'),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.ForeignKey(blank=True, db_column='status_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.leadstatus'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['tenant_id'], name='idx_lead_activities_tenant_id'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['lead'], name='idx_lead_activities_lead_id'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['type'], name='idx_lead_activities_type'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['happened_at'], name='idx_lead_activities__at'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['by_user_id'], name='idx_lead_activities_by_user_id'),
        ),
        migrations.AddIndex(
            model_name='leadorder',
            index=models.Index(fields=['tenant_id'], name='idx_lead_orders_tenant_id'),
        ),
        migrations.AddIndex(
            model_name='leadorder',
            index=models.Index(fields=['status', 'position'], name='idx_lead_orders_status_id_pos'),
        ),
        migrations.AddIndex(
            model_name='leadorder',
            index=models.Index(fields=['lead'], name='idx_lead_orders_lead_id'),
        ),
        migrations.AlterUniqueTogether(
            name='leadorder',
            unique_together={('lead', 'status')},
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tenant_id'], name='idx_leads_tenant_id'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='idx_leads_status_id'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['priority'], name='idx_leads_priority'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['owner_user_id'], name='idx_leads_owner_user_id'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to'], name='idx_leads_assigned_to'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone'], name='idx_leads_phone'),
        ),
    ]
