# Generated by Django 4.2.27 on 2026-01-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_score',
            field=models.IntegerField(blank=True, default=0, help_text='Lead score from 0 to 100', null=True),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(check=models.Q(('lead_score__isnull', True), models.Q(('lead_score__gte', 0), ('lead_score__lte', 100)), _connector='OR'), name='leads_score_range_check'),
        ),
    ]
