# Generated by Django 4.2.28 on 2026-03-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_lead_lead_score_lead_leads_score_range_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="bhk_preference",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="broker_id",
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="budget_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="budget_min",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="preferred_localities",
            field=models.JSONField(
                blank=True, help_text="List of preferred areas/localities", null=True
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="preferred_project_id",
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="re_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BROKER", "Broker / Channel Partner"),
                    ("WEBSITE", "Website"),
                    ("META_ADS", "Meta Ads"),
                    ("GOOGLE_ADS", "Google Ads"),
                    ("WALK_IN", "Walk In"),
                    ("REFERRAL", "Referral"),
                    ("WHATSAPP", "WhatsApp"),
                    ("PHONE", "Phone Enquiry"),
                    ("HOARDING", "Hoarding / Outdoor"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="shortlisted_unit_id",
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="site_visit_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="token_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="leadactivity",
            name="type",
            field=models.CharField(
                choices=[
                    ("CALL", "Call"),
                    ("EMAIL", "Email"),
                    ("MEETING", "Meeting"),
                    ("NOTE", "Note"),
                    ("SMS", "SMS"),
                    ("SITE_VISIT", "Site Visit"),
                    ("WHATSAPP", "WhatsApp"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
