# Generated by Django 4.2.28 on 2026-03-03 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant ID for multi-tenancy')),
                ('user_id', models.UUIDField(db_index=True, help_text='User who owns this connection')),
                ('name', models.CharField(help_text='User-friendly name for this connection (e.g., "Marketing Leads Sheet")', max_length=200)),
                ('status', models.CharField(choices=[('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('EXPIRED', 'Expired'), ('ERROR', 'Error')], default='DISCONNECTED', help_text='Connection status', max_length=20)),
                ('access_token_encrypted', models.TextField(blank=True, help_text='Encrypted OAuth access token', null=True)),
                ('refresh_token_encrypted', models.TextField(blank=True, help_text='Encrypted OAuth refresh token', null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='When the access token expires', null=True)),
                ('connection_data', models.JSONField(blank=True, help_text='Additional connection metadata (account email, sheet IDs, etc.)', null=True)),
                ('last_error', models.TextField(blank=True, help_text='Last error message if any', null=True)),
                ('last_error_at', models.DateTimeField(blank=True, help_text='When the last error occurred', null=True)),
                ('connected_at', models.DateTimeField(blank=True, help_text='When the connection was established', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='When this connection was last used', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'connections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant ID for multi-tenancy')),
                ('user_id', models.UUIDField(db_index=True, help_text='User who created this workflow')),
                ('name', models.CharField(help_text='Workflow name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Workflow description', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this workflow is active')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When workflow was deleted', null=True)),
                ('last_executed_at', models.DateTimeField(blank=True, help_text='When workflow was last executed', null=True)),
                ('last_execution_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], help_text='Status of last execution', max_length=20, null=True)),
                ('total_executions', models.IntegerField(default=0, help_text='Total number of executions')),
                ('successful_executions', models.IntegerField(default=0, help_text='Number of successful executions')),
                ('failed_executions', models.IntegerField(default=0, help_text='Number of failed executions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(db_column='connection_id', help_text='The connection this workflow uses', on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='integrations.connection')),
            ],
            options={
                'db_table': 'workflows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('CREATE_LEAD', 'Create Lead'), ('UPDATE_LEAD', 'Update Lead'), ('CREATE_TASK', 'Create Task'), ('SEND_EMAIL', 'Send Email'), ('WEBHOOK', 'Send Webhook')], help_text='Type of action to perform', max_length=20)),
                ('order', models.IntegerField(default=1, help_text='Execution order (lower executes first)')),
                ('action_config', models.JSONField(help_text='Action-specific configuration (target model, default values, etc.)')),
                ('conditions', models.JSONField(blank=True, help_text='Conditions that must be met for action to execute', null=True)),
                ('retry_on_failure', models.BooleanField(default=True, help_text='Whether to retry this action on failure')),
                ('max_retries', models.IntegerField(default=3, help_text='Maximum number of retries')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.ForeignKey(db_column='workflow_id', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='integrations.workflow')),
            ],
            options={
                'db_table': 'workflow_actions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Integration name (e.g., Google Sheets)', max_length=100, unique=True)),
                ('type', models.CharField(choices=[('GOOGLE_SHEETS', 'Google Sheets'), ('WEBHOOK', 'Webhook'), ('ZAPIER', 'Zapier'), ('API', 'Generic API'), ('EMAIL', 'Email')], help_text='Type of integration', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of what this integration does', null=True)),
                ('icon_url', models.URLField(blank=True, help_text='URL to integration icon/logo', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this integration is available')),
                ('requires_oauth', models.BooleanField(default=False, help_text='Whether OAuth is required')),
                ('oauth_config', models.JSONField(blank=True, help_text='OAuth configuration (client_id, scopes, etc.)', null=True)),
                ('api_config', models.JSONField(blank=True, help_text='API configuration (endpoints, headers, etc.)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'integrations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['type'], name='idx_integrations_type'), models.Index(fields=['is_active'], name='idx_integrations_active')],
            },
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant ID for multi-tenancy')),
                ('execution_id', models.UUIDField(db_index=True, help_text='Unique execution identifier', unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], default='PENDING', help_text='Execution status', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When execution started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When execution completed', null=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Execution duration in milliseconds', null=True)),
                ('trigger_data', models.JSONField(blank=True, help_text='Data that triggered the workflow (e.g., new row data)', null=True)),
                ('result_data', models.JSONField(blank=True, help_text='Result of the execution (created lead ID, etc.)', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed', null=True)),
                ('error_traceback', models.TextField(blank=True, help_text='Full error traceback', null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('is_retry', models.BooleanField(default=False, help_text='Whether this is a retry execution')),
                ('parent_execution_id', models.UUIDField(blank=True, db_index=True, help_text='Parent execution ID if this is a retry', null=True)),
                ('execution_steps', models.JSONField(blank=True, help_text='Detailed step-by-step execution log', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.ForeignKey(db_column='workflow_id', on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='integrations.workflow')),
            ],
            options={
                'db_table': 'execution_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DuplicateDetectionCache',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant ID for multi-tenancy')),
                ('source_identifier', models.CharField(help_text='Unique identifier from source (e.g., sheet_id:row_number)', max_length=500)),
                ('created_object_type', models.CharField(help_text='Type of object created (Lead, Task, etc.)', max_length=50)),
                ('created_object_id', models.BigIntegerField(help_text='ID of created object')),
                ('source_data_hash', models.CharField(help_text='Hash of source data for change detection', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.ForeignKey(db_column='workflow_id', on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_cache', to='integrations.workflow')),
            ],
            options={
                'db_table': 'duplicate_detection_cache',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='connection',
            name='integration',
            field=models.ForeignKey(db_column='integration_id', on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='integrations.integration'),
        ),
        migrations.CreateModel(
            name='WorkflowTrigger',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('NEW_ROW', 'New Row Added'), ('UPDATED_ROW', 'Row Updated'), ('WEBHOOK_RECEIVED', 'Webhook Received'), ('SCHEDULE', 'Scheduled'), ('MANUAL', 'Manual Trigger')], help_text='Type of trigger', max_length=20)),
                ('trigger_config', models.JSONField(help_text='Trigger configuration (sheet_id, sheet_name, column_mappings, etc.)')),
                ('poll_interval_minutes', models.IntegerField(default=10, help_text='How often to poll for changes (in minutes)')),
                ('last_checked_at', models.DateTimeField(blank=True, help_text='When trigger was last checked', null=True)),
                ('last_processed_record', models.JSONField(blank=True, help_text='Last processed record metadata (row number, timestamp, etc.)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.OneToOneField(db_column='workflow_id', on_delete=django.db.models.deletion.CASCADE, related_name='trigger', to='integrations.workflow')),
            ],
            options={
                'db_table': 'workflow_triggers',
                'indexes': [models.Index(fields=['trigger_type'], name='idx_workflow_triggers_type'), models.Index(fields=['last_checked_at'], name='idx_workflow_triggers_checked')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_field', models.CharField(help_text='Source field name (e.g., column name from sheet)', max_length=200)),
                ('destination_field', models.CharField(help_text='Destination field name (e.g., lead.name, lead.email)', max_length=200)),
                ('transformation', models.JSONField(blank=True, help_text='Transformation rules (trim, lowercase, format, etc.)', null=True)),
                ('default_value', models.TextField(blank=True, help_text='Default value if source field is empty', null=True)),
                ('is_required', models.BooleanField(default=False, help_text='Whether this field is required')),
                ('validation_rules', models.JSONField(blank=True, help_text='Validation rules (regex, min/max length, etc.)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow_action', models.ForeignKey(db_column='workflow_action_id', on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='integrations.workflowaction')),
            ],
            options={
                'db_table': 'workflow_mappings',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['workflow_action'], name='idx_workflow_mappings_action')],
            },
        ),
        migrations.AddConstraint(
            model_name='workflowmapping',
            constraint=models.UniqueConstraint(fields=('workflow_action', 'destination_field'), name='unique_mapping_per_destination'),
        ),
        migrations.AddIndex(
            model_name='workflowaction',
            index=models.Index(fields=['workflow', 'order'], name='idx_workflow_actions_order'),
        ),
        migrations.AddIndex(
            model_name='workflowaction',
            index=models.Index(fields=['action_type'], name='idx_workflow_actions_type'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['tenant_id'], name='idx_workflows_tenant'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['user_id'], name='idx_workflows_user'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['is_active'], name='idx_workflows_active'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['is_deleted'], name='idx_workflows_deleted'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['tenant_id', 'is_active', 'is_deleted'], name='idx_workflows_active_lookup'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['tenant_id'], name='idx_exec_logs_tenant'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['workflow'], name='idx_exec_logs_workflow'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['status'], name='idx_exec_logs_status'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['started_at'], name='idx_exec_logs_started'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['-started_at'], name='idx_exec_logs_started_desc'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['tenant_id', 'workflow', '-started_at'], name='idx_exec_logs_lookup'),
        ),
        migrations.AddIndex(
            model_name='duplicatedetectioncache',
            index=models.Index(fields=['tenant_id'], name='idx_dup_cache_tenant'),
        ),
        migrations.AddIndex(
            model_name='duplicatedetectioncache',
            index=models.Index(fields=['workflow'], name='idx_dup_cache_workflow'),
        ),
        migrations.AddIndex(
            model_name='duplicatedetectioncache',
            index=models.Index(fields=['source_identifier'], name='idx_dup_cache_source_id'),
        ),
        migrations.AddConstraint(
            model_name='duplicatedetectioncache',
            constraint=models.UniqueConstraint(fields=('workflow', 'source_identifier'), name='unique_source_per_workflow'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['tenant_id'], name='idx_connections_tenant'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['user_id'], name='idx_connections_user'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['status'], name='idx_connections_status'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['tenant_id', 'user_id'], name='idx_connections_tenant_user'),
        ),
    ]
