# Generated by Django 4.2.28 on 2026-03-02 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0003_add_re_fields_to_lead"),
        ("inventory", "0001_initial_inventory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("booking_date", models.DateField()),
                (
                    "token_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "payment_plan_type",
                    models.CharField(
                        choices=[
                            ("20_80", "20:80 Plan"),
                            ("CONSTRUCTION_LINKED", "Construction Linked Plan"),
                            ("CUSTOM", "Custom Plan"),
                        ],
                        default="CUSTOM",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("TOKEN_PAID", "Token Paid"),
                            ("AGREEMENT_DONE", "Agreement Done"),
                            ("REGISTERED", "Registered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("agreement_date", models.DateField(blank=True, null=True)),
                ("registration_date", models.DateField(blank=True, null=True)),
                ("cancellation_date", models.DateField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("owner_user_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lead",
                    models.ForeignKey(
                        db_column="lead_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="crm.lead",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        db_column="unit_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="inventory.unit",
                    ),
                ),
            ],
            options={
                "db_table": "bookings",
            },
        ),
        migrations.CreateModel(
            name="PaymentMilestone",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("milestone_name", models.TextField()),
                ("due_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage of total amount this milestone represents",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("PARTIALLY_PAID", "Partially Paid"),
                            ("OVERDUE", "Overdue"),
                            ("WAIVED", "Waived"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "received_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("received_date", models.DateField(blank=True, null=True)),
                ("reference_no", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("order_index", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        db_column="booking_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "db_table": "payment_milestones",
                "ordering": ["order_index", "due_date"],
                "indexes": [
                    models.Index(fields=["tenant_id"], name="idx_milestones_tenant_id"),
                    models.Index(fields=["booking"], name="idx_milestones_booking_id"),
                    models.Index(fields=["status"], name="idx_milestones_status"),
                    models.Index(fields=["due_date"], name="idx_milestones_due_date"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["tenant_id"], name="idx_bookings_tenant_id"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["lead"], name="idx_bookings_lead_id"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["unit"], name="idx_bookings_unit_id"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["status"], name="idx_bookings_status"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["booking_date"], name="idx_bookings_date"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["owner_user_id"], name="idx_bookings_owner_user_id"
            ),
        ),
    ]
